### ISSUE TITLE
Getting HTTP 500 Error on online REST page when using findlicenseinrdf get or post

### ISSUE THREAD

**Issue by kartgk** [oeg-upm/licensius#1]
Trying to check licensius working for my ontology 

https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/Corporations/Corporations/

When I use the URL in the REST API it is showing "500" or "No Response From Server".  

http://licensius.com/apidoc/index.html

Can you please check and let me know.

**Comment by vroddon** [comment]
Thanks for your interest. I have tried to locally reproduce the problem with little luck: when I invoke the service with the following URI, the service works as deemed.

http://terecom2017.lynx-project.eu/test2.rdf

Perhaps it is related to the URI being "https".
https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/Corporations/Corporations/

Still working on this...

**Comment by kartgk** [comment]
I tried the restful service on the web page  -  as you have mentioned it works with 'http'.  Can you please fix service to handle 'https'.  We are using Widoco - which is trying to resolve using our ontologies which are all prefixed with https.

**Comment by kartgk** [comment]
@vroddon Can you please take a look.

**Comment by vroddon** [comment]
The problem has just been fixed, @kartgk 
Thanks for your patience, and thanks for reporting.
