### ISSUE TITLE
licensius-core to be deprecated

### ISSUE THREAD

**Issue by vroddon** [oeg-upm/licensius#14]
too old, little added value
in use by rdflicense, though. 
Use jodrlapi instead.

**Comment by dgarijo** [comment]
Does this mean the service is going to be deprecated? If so, I need to know for Widoco.
In fact, what I would love would be to import a lib so I don't have to call the ws, not sure if that's possible.

**Comment by vroddon** [comment]
Thanks for your interest! I do not plan to withdraw the service, but update the underlying libraries. They are too old and too slow. Thanks for the interest again!
