### ISSUE TITLE
Status Licensius.com requested

### ISSUE THREAD

**Issue by janvlug** [oeg-upm/licensius#29]
I am trying to use Licensius as integrated in [WIDOCO](https://github.com/dgarijo/Widoco). What is the current status of the Licensius web services?

It seems that the calls to the API do not give responses. See for example:
`http://licensius.com/apidoc/index.html#!/license/get_license_list`
Which returns:
```
{
  "error": "no response from server"
}
```

**Comment by vroddon** [comment]
Services are being provided in http://www.licensius.appspot.com/
